<!DOCTYPE Student [
  <!ELEMENT Student (Name, Address, Email, Contact)>
  <!ELEMENT Name (#PCDATA)>
  <!ELEMENT Address (#PCDATA)>
  <!ELEMENT Email (#PCDATA)>
  <!ELEMENT Contact (#PCDATA)>
]>
<Student>
  <Name>Praful Shrestha</Name>
  <Address>Nepal</Address>
  <Email>hellopraful@email.com</Email>
  <Contact>7854236958</Contact>
</Student>
